from enum import Enum
class Categories(Enum):
    TECHNOLOGY = 'Technology'
    PROGRAMMING = 'Programming'
    SCIENCE = 'Science'
    FASHION = 'Fashion'
    POLITICS = 'Politics'
    HEALTH_AND_FITNESS = 'Health and Fitness'
    ENTERTAINMENT = 'Entertainment'
    TRAVEL = 'Travel'
    FOOD_AND_COOKING = 'Food and Cooking'
    BUSINESS_AND_FINANCE = 'Business and Finance'
    EDUCATION = 'Education'
    SPORTS = 'Sports'
    ART_AND_CULTURE = 'Art and Culture'
    SCIENCE_AND_NATURE = 'Science and Nature'
    HOME_AND_GARDEN = 'Home and Garden'
    AUTOMOTIVE = 'Automotive'
    PETS_AND_ANIMALS = 'Pets and Animals'
    SOCIAL_ISSUES_AND_ACTIVISM = 'Social Issues and Activism'
    HISTORY_AND_HERITAGE = 'History and Heritage'
    LITERATURE_AND_WRITING = 'Literature and Writing'
    PHILOSOPHY_AND_SPIRITUALITY = 'Philosophy and Spirituality'
